#!/usr/bin/env python
from powa import make_app
import tornado.ioloop
from tornado.options import options, Error as terror
from powa.options import parse_options

if __name__ == "__main__":
    application = make_app(debug=False, gzip=True, compress_response=True)
    application.listen(options.port, address=options.address)
    tornado.ioloop.IOLoop.instance().start()
